version: "3.9"

services:
  db:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp
      MYSQL_PASSWORD: example
    volumes:
      - dbdata:/var/lib/mysql
  wordpress:
    image: wordpress:php8.2-fpm
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wp-content:/var/www/html/wp-content
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wordpress

volumes:
  dbdata: